### ISSUE TITLE
Do not seems to work with Leaflet 1.0.3

### ISSUE THREAD

**Issue by Victs** [cloudybay/leaflet.latlng-graticule#6]
Just changed Leaflet js version to 1.0.3 in Demo html. Looks that some callback function was not be able to be registered properly. Sorry to say, was not able to resolve it by myself.

**Comment by gn00672312** [comment]
Thank you for your report. This plugin is for Leaflet 0.7.7. We haven't upgraded our leaflet yet. I'll check the issue sometime during the week.

**Comment by gn00672312** [comment]
Good day. This issue was solved. L.LatLngGraticule extended from L.Class at Leaflet 0.7.7, but new version of Leaflet used L.Layer to replace L.Class. So, we released v1.0 and v1.1 to support it. You could update to v1.1 now.

**Comment by Victs** [comment]
Thank you for kind reply and quick resolution. Works fine with 1.0.3
